spring:
  application:
    name: medication-calendar
  datasource:
    url: jdbc:h2:mem:medications
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    com.example.medication: INFO
    org.hibernate.SQL: DEBUG